import kotlin.test.Test
import kotlin.test.assertEquals

class Day07Test {
    private val testData = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.trimIndent()

    @Test
    fun part1() {
        assertEquals(21, Day07.part1(testData))
    }

    @Test
    fun part2() {
        assertEquals(40, Day07.part2(testData))
    }
}
